workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plexapi:
        inputs:
            - location: ./plex-api-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi
targets: {}
