type: object
description: |
  The Meta object is only included in the response if the `includeMeta` parameter is set to `1`.
properties:
  Type:
    type: array
    items:
      type: object
      required:
        - key
        - type
        - title
        - active
      properties:
        key:
          type: string
          example: "/library/sections/2/all?type=2"
        type:
          type: string
          example: "show"
        title:
          type: string
          example: "TV Shows"
        active:
          type: boolean
          example: false
        Filter:
          type: array
          items:
            type: object
            required:
              - filter
              - filterType
              - key
              - title
              - type
            properties:
              filter:
                type: string
                example: "genre"
              filterType:
                type: string
                example: "string"
              key:
                type: string
                example: "/library/sections/2/genre?type=2"
              title:
                type: string
                example: "Genre"
              type:
                type: string
                example: "filter"
        Sort:
          type: array
          items:
            type: object
            required:
              - key
              - title
              - defaultDirection
            properties:
              default:
                type: string
                example: "asc"
              active:
                type: boolean
                example: false
              activeDirection:
                $ref: "../models/common/PlexSortDirection.yaml"
              defaultDirection:
                $ref: "../models/common/PlexSortDirection.yaml"
              descKey:
                type: string
                example: "titleSort:desc"
              firstCharacterKey:
                type: string
                example: "/library/sections/2/firstCharacter"
              key:
                type: string
                example: "titleSort"
              title:
                type: string
                example: "Title"
        Field:
          type: array
          items:
            type: object
            required:
              - key
              - title
              - type
            properties:
              key:
                type: string
                example: "show.title"
              title:
                type: string
                example: "Show Title"
              type:
                type: string
                example: "string"
              subType:
                type: string
                example: "rating"
  FieldType:
    type: array
    items:
      type: object
      required:
        - type
        - Operator
      properties:
        type:
          type: string
          example: "tag"
        Operator:
          type: array
          items:
            type: object
            required:
              - key
              - title
            properties:
              key:
                type: string
                example: "="
              title:
                type: string
                example: "is"
