name: Linting
"on":
  pull_request:
    paths:
      - pms-spec.yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli

      - name: Dereference Plex Media Server Specification
        run: |
          swagger-cli bundle --dereference pms-spec.yaml -t yaml -o plex-media-server-spec-dereferenced.yaml

      - name: Install Speakeasy CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/speakeasy-api/speakeasy/main/install.sh | sh

      - name: OpenAPI Lint
        run: speakeasy lint openapi -s plex-media-server-spec-dereferenced.yaml
